Use a private lookup object:
The publicLookup surprisingly causes a loader constraint violation
on Java 14 (but works on 11 through 13). The error appears on the
second lookup (e.g., when a second testkit instance is created):

```
java.lang.LinkageError: loader constraint violation: when resolving method
'com.exonum.binding.fakeservice.Transactions$PutTransactionArgs com.exonum.binding.fakeservice.Transactions$PutTransactionArgs.parseFrom(byte[])'
the class loader 'bootstrap' of the current class, java/lang/Object, and
the class loader org.pf4j.PluginClassLoader @1d96d872 for the method's defining class,
com/exonum/binding/fakeservice/Transactions$PutTransactionArgs,
have different Class objects for the type com/exonum/binding/fakeservice/Transactions$PutTransactionArgs
used in the signature (java.lang.Object is in module java.base of loader 'bootstrap';
com.exonum.binding.fakeservice.Transactions$PutTransactionArgs is in unnamed module
of loader org.pf4j.PluginClassLoader @1d96d872, parent loader 'app')
```