Workaround the javac 8 bug:
Apparently, it does not like this static import, causing
an obscure compilation error:

https://travis-ci.com/exonum/exonum-java-binding/jobs/270302809#L4823

```
[ERROR] /Users/travis/build/exonum/exonum-java-binding/exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/TransactionInvokerTest.java:[104,40] cannot find symbol

  symbol:   class Service

  location: class com.exonum.binding.core.runtime.TransactionInvokerTest
```

Qualified access (BasicService.TRANSACTION_ID) solves
the issue; but I moved the constants to the tests
to not need them.